"""Add SystemSetting table

Revision ID: 35b1fac61cb4
Revises: e4803a13d646
Create Date: 2025-10-27 18:15:41.434045

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "35b1fac61cb4"
down_revision = "e4803a13d646"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system_settings")
    # ### end Alembic commands ###
