"""Enhance ApiKey model and add admin flag

Revision ID: 3c565ef4ba1e
Revises: a9b5741ecf06
Create Date: 2025-10-15 10:15:21.353971

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3c565ef4ba1e"
down_revision = "a9b5741ecf06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_admin", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_column("is_admin")

    # ### end Alembic commands ###
